### ISSUE TITLE
Showing a Deprecated error message in Q2A 1.8.3

### ISSUE THREAD

**Issue by s1-ranjan** [JacksiroKe/Q2A-Blog-Post-Plugin#10]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; qa_layer_1_from_blog_admin_php has a deprecated constructor in /home/orml/public_html/jobs.Ask-Gurus/qa-include/qa-base.php(720) : eval()'d code on line 22
of /home/orml/public_html/jobs.Ask-Gurus/qa-plugin/blog-post/blog-admin.php

**Comment by JacksiroKe** [comment]
fixed in the latest commit
