### ISSUE TITLE
Database initialisation issue with Q2A 1.8.3

### ISSUE THREAD

**Issue by rohitagarwal88** [JacksiroKe/Q2A-Blog-Post-Plugin#9]
I installed the plugin got the issue with database initialization:

`Database query error 1171
All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

CREATE TABLE IF NOT EXISTS qa_blog_users (
`userid` INT(10) UNSIGNED DEFAULT NULL,
`lastposted` DATETIME NOT NULL,
`pcount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`ccount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`dcount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
`points` INT NOT NULL DEFAULT 0,
`cselects` MEDIUMINT NOT NULL DEFAULT 0,
`cselecteds` MEDIUMINT NOT NULL DEFAULT 0,
`pupvotes` MEDIUMINT NOT NULL DEFAULT 0,
`pdownvotes` MEDIUMINT NOT NULL DEFAULT 0,
`cupvotes` MEDIUMINT NOT NULL DEFAULT 0,
`cdownvotes` MEDIUMINT NOT NULL DEFAULT 0,
`pvoteds` INT NOT NULL DEFAULT 0,
`cvoteds` INT NOT NULL DEFAULT 0,
`upvoteds` INT NOT NULL DEFAULT 0,
`downvoteds` INT NOT NULL DEFAULT 0,
`kickeduntil` DATETIME NOT NULL,
PRIMARY KEY (`userid`),
KEY `userid` (`userid`),
KEY `points` (`points`),
KEY `active` (`lastposted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

` 
@Jacksiro : Please help me with the issue

**Comment by Jacksiro** [comment]
Hi mate please give two days I will check and get back to you asap. Am not in a position to help at the moment. So just uninstall the plugin and wait for my feedback in two days time

**Comment by rohitagarwal88** [comment]
@Jacksiro : Did you get a chance to look at the issue?

**Comment by gnomezgrave** [comment]
Change

`userid INT(10) UNSIGNED DEFAULT NULL,`

to 

`userid INT(10) UNSIGNED NOT NULL,`

**Comment by JacksiroKe** [comment]
Sorry mates, I am sorry I got busy with other projects elsewhere and forgot about this one. I managed to push some new updates and the database initialization issue is no more
